# Generated by Django 3.0 on 2022-09-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_contrato', models.FloatField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
