# Generated by Django 3.0 on 2022-09-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20220915_2112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Cliente',
        ),
    ]
